### ISSUE TITLE
Type checking with Agda 2.6.0.x releases

### ISSUE THREAD

**Issue by AndrasKovacs** [jashug/ConstructingII#1]
With Agda 2.6.0.1, the Primitive.agda file throws the following error:

```
Cannot create a module containing a copy of primTransp
when checking the module application
module Unsafe' (dummy : Set₁) = Postulates
```

Since now there are official Agda releases with `--cubical`, it would be good to be compatible with them.

**Comment by jashug** [comment]
Thank you for pointing this out. I just pushed a commit adapting to the released version of Agda 2.6.0.1.
